Skip unit tests when running SonarQube analysis to avoid build failure caused by Windows-only HecLib (#56)
Should resolve the following build error during SonarQube build:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':wrims-ide:test'.
> There were failing tests. See the report at: file:///home/runner/work/wrims-gui/wrims-gui/wrims-ide/build/reports/tests/test/index.html

* Try:
> Run with --scan to get full insights.

BUILD FAILED in 52s
UtilsTest > testUtilsGetTSContainer1DayFail() FAILED
    java.lang.UnsatisfiedLinkError at UtilsTest.java:72

UtilsTest > testUtilsGetTSContainerDss6() FAILED
    java.lang.NoClassDefFoundError at UtilsTest.java:29
        Caused by: java.lang.ExceptionInInitializerError at UtilsTest.java:72

UtilsTest > testUtilsGetTSContainerDss7() FAILED
    java.lang.NoClassDefFoundError at UtilsTest.java:50
        Caused by: java.lang.ExceptionInInitializerError at UtilsTest.java:72
gradle/actions: Writing build results to /home/runner/work/_temp/.gradle-actions/build-results/__run_2-1758910306828.json